# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e15681a5f10838c8e743fb2991a1b7e751e972273d8436f48f82def598851ff80b05b238c4b423849777045a0eed8454bfe6574c36404b291a0b4e569af119c2

test:
  secret_key_base: c7007229258faa200bf3bfd28638515a90db0742860b85a018f68c3fe14f11c3d9de1f340afcb4d0280f920c29d53230e5814098f134ea6694c312a26b7cde67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
